// ponytail: thin TS bridge over Rust WASM.
// The WASM module lives at src/__wasm__/fsrs_bindings (generated by wasm-pack).

export type { FsrsCard, ReviewLogEntry } from './__wasm__/fsrs_bindings';

import type { FsrsCard, ReviewLogEntry } from './__wasm__/fsrs_bindings';
import init, { FsrsScheduler } from './__wasm__/fsrs_bindings';

let _init: Promise<void> | null = null;
let _scheduler: Scheduler | null = null;
let _loaded = false;

export async function ensureLoaded(): Promise<void> {
  if (!_loaded) {
    _init = (async () => {
      await init();
      _loaded = true;
    })().catch((e) => {
      _init = null;
      _loaded = false;
      throw e;
    });
  }
  return _init!;
}

export type Rating = 'again' | 'hard' | 'good' | 'easy';

// ponytail: no parse on Rust side — TS owns the union type.
export function parseRating(s: string): Rating | undefined {
  if (['again', 'hard', 'good', 'easy'].includes(s)) return s as Rating;
  return undefined;
}

export interface SchedulerDefaults {
  initialStability?: number;
  initialDifficulty?: number;
  againFactor?: number;
  hardFactor?: number;
  goodFactor?: number;
  easyFactor?: number;
  hardDiffDelta?: number;
  goodDiffDelta?: number;
  easyDiffDelta?: number;
}

export class Scheduler {
  private _scheduler: FsrsScheduler;

  constructor() {
    this._scheduler = new FsrsScheduler();
  }

  async createCard(opts: { id: string; now?: number }): Promise<FsrsCard> {
    await ensureLoaded();
    return this._scheduler.create_card(opts.id, opts.now ?? Date.now());
  }

  async reviewCard(opts: { card: FsrsCard; rating: Rating; now?: number }): Promise<ReviewLogEntry> {
    await ensureLoaded();
    return this._scheduler.review_card(opts.card, opts.rating, opts.now ?? Date.now());
  }

  async retrievability(card: FsrsCard, now: number): Promise<number> {
    await ensureLoaded();
    return FsrsScheduler.retrievability(card, now);
  }

  async due(now?: number): Promise<FsrsCard[]> {
    await ensureLoaded();
    return this._scheduler.get_due(now ?? Date.now());
  }

  async all(): Promise<FsrsCard[]> {
    await ensureLoaded();
    return this._scheduler.all_cards();
  }
}

export function getScheduler(): Scheduler {
  if (!_scheduler) _scheduler = new Scheduler();
  return _scheduler;
}
