"use strict";
// ponytail: thin TS bridge over Rust WASM.
// The WASM module lives at src/__wasm__/fsrs_bindings (generated by wasm-pack).
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Scheduler = void 0;
exports.ensureLoaded = ensureLoaded;
exports.parseRating = parseRating;
exports.getScheduler = getScheduler;
const fsrs_bindings_1 = __importStar(require("./__wasm__/fsrs_bindings"));
let _init = null;
let _scheduler = null;
let _loaded = false;
async function ensureLoaded() {
    if (!_loaded) {
        _init = (async () => {
            await (0, fsrs_bindings_1.default)();
            _loaded = true;
        })().catch((e) => {
            _init = null;
            _loaded = false;
            throw e;
        });
    }
    return _init;
}
// ponytail: no parse on Rust side — TS owns the union type.
function parseRating(s) {
    if (['again', 'hard', 'good', 'easy'].includes(s))
        return s;
    return undefined;
}
class Scheduler {
    _scheduler;
    constructor() {
        this._scheduler = new fsrs_bindings_1.FsrsScheduler();
    }
    async createCard(opts) {
        await ensureLoaded();
        return this._scheduler.create_card(opts.id, opts.now ?? Date.now());
    }
    async reviewCard(opts) {
        await ensureLoaded();
        return this._scheduler.review_card(opts.card, opts.rating, opts.now ?? Date.now());
    }
    async retrievability(card, now) {
        await ensureLoaded();
        return fsrs_bindings_1.FsrsScheduler.retrievability(card, now);
    }
    async due(now) {
        await ensureLoaded();
        return this._scheduler.get_due(now ?? Date.now());
    }
    async all() {
        await ensureLoaded();
        return this._scheduler.all_cards();
    }
}
exports.Scheduler = Scheduler;
function getScheduler() {
    if (!_scheduler)
        _scheduler = new Scheduler();
    return _scheduler;
}
//# sourceMappingURL=index.js.map